version: '3.8'

services:

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - 8000

    ports:
      - 8180:8000

  # flask:
  #   build: ./flask
  #   volumes:
  #     - ./flask:/usr/src/app
  #   expose:
  #     - 5000

  #   ports:
  #     - 8181:5000

  # frontend:
  #   stdin_open: true
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   expose:
  #     - 5173
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - backend

  #   ports:
  #     - 5173:5173

  # reverse_proxy:
  #   build: ./nginx
  #   ports:
  #     - 81:80
  #   depends_on:
  #     - backend
  #     - frontend
